### ISSUE TITLE
Cann't run in Mac with tensorflow 0.12.1

### ISSUE THREAD

**Issue by TomorrowIsAnOtherDay** [devsisters/neural-combinatorial-rl-tensorflow#1]
Traceback (most recent call last):
  File "main.py", line 5, in <module>
    from trainer import Trainer
  File "/Users/yobobobo/Firework/reinforce_learning/neural-combinatorial-rl-tensorflow/trainer.py", line 7, in <module>
    from model import Model
  File "/Users/yobobobo/Firework/reinforce_learning/neural-combinatorial-rl-tensorflow/model.py", line 4, in <module>
    from layers import *
  File "/Users/yobobobo/Firework/reinforce_learning/neural-combinatorial-rl-tensorflow/layers.py", line 7, in <module>
    LSTMCell = rnn.LSTMCell
AttributeError: 'module' object has no attribute 'LSTMCell'

**Comment by carpedm20** [comment]
This project is temporally stopped after I saw the sentence that authors will release the code with TensorFlow.

**Comment by TomorrowIsAnOtherDay** [comment]
Thanks for replying and your great job.
